env_name: "maze2d-medium-v1"
max_path_length: 600

planner_horizon: 32
stride: 15
planner_temperature: 1.0
planner_target_return: 1.0 # Placeholder. Require grid tuning for CFG
planner_w_cfg: 1.0 # Placeholder. Require grid tuning for CG and CFG